# Generated by Django 4.2.2 on 2023-06-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='jobsid',
            new_name='jobid',
        ),
    ]
